config/routes.rb
Rails.application.routes.draw do
  get 'scrapings/index'

  get 'movies/index'

  get 'movies/show'

  devise_for :users, path: "admin/users"
  root 'home#index'
  get 'home/answered'

  #管理者のページ
  namespace :admin do
    resources :users
    resources :movies
    resources :scrapings
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  screening_time :string(255)
#  image_url      :string(255)
#  category_id    :integer
#  total_point    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Movie < ApplicationRecord
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  answer     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
end

app/models/question1.rb
# == Schema Information
#
# Table name: question1s
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  answer     :string(255)      not null
#  point      :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question1 < ApplicationRecord
end

app/models/question2.rb
# == Schema Information
#
# Table name: question2s
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  answer     :string(255)      not null
#  point      :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question2 < ApplicationRecord
end

app/models/question3.rb
# == Schema Information
#
# Table name: question3s
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  answer     :string(255)      not null
#  point      :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question3 < ApplicationRecord
end

app/models/scraping.rb
# == Schema Information
#
# Table name: scrapings
#
#  id             :integer          not null, primary key
#  movie_title    :string(255)
#  screening_time :string(255)
#  image_url      :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Scraping < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: "katyou", password: "holiday" if Rails.env.staging? || Rails.env.Production?

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def answered
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def delete
  end
end

app/controllers/scrapings_controller.rb
class ScrapingsController < ApplicationController
  before_action :set_scraping
  def index
  end

  def edit
  end

  def destroy
  end

  private
  def set_scraping
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/scrapings_helper.rb
module ScrapingsHelper
end

app/views/home/_question.html.haml
-if @question == nil
  %q_title= 質問１
  %question
    = form_for @question do |f|
      = f.label "質問１"
      = f.check_box :answer, class: "check_box_label"

-elsif @question == 2

-elsif @question == 3

-elsif @question == 4

app/views/home/answered.html.haml
%h1 Home#answered
%p Find me in app/views/home/answered.html.haml

app/views/home/index.html.haml
%center
  %h1 空き時間コンシュルジュ
  .container
    .desc このサービスは質問に答えることで、数分後に上映される映画の中から一番最適な映画を提供いたします。
      %br
      .subdesc このサービスは、大分県のアミュプラザ大分の映画情報のみ提供しています。

.question
  .container
    = render :partial 'question'

app/views/layouts/_header.html.haml
%header
  .container
    %a.image{href: admin_users_path} 管理画面メニュー
    %header_menu
      =link_to "映画一覧", admin_movies_path, class: "btn-left btn"
      =link_to "スクレイピング結果一覧", admin_scraiping_path, class: "btn-left btn"
      =link_to "ユーザー情報", users_path, class: "btn-left btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HolidayConcierge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    -if current_user?
      = render 'layuts/header'
    = yield
    -unless current_user?
      = render 'layouts/header'

app/views/movies/index.html.haml
%h1 Movies#index
%p Find me in app/views/movies/index.html.haml

app/views/movies/show.html.haml
%h1 Movies#show
%p Find me in app/views/movies/show.html.haml

app/views/scrapings/index.html.haml
%h1 Scrapings#index
%p Find me in app/views/scrapings/index.html.haml